@include('layouts.admissionlists-details.head')
@include('general.nav')
@include('layouts.admissionlists-details.header')
@include('layouts.admissionlists-details.content')
@include('general.footer')
@include('general.scripts')