@include('layouts.admissionlists.head')
@include('general.nav')
@include('layouts.admissionlists.header')
@include('layouts.admissionlists.container')
@include('general.footer')
@include('general.scripts')