@include('layouts.notices-details.head')
@include('general.nav')
@include('layouts.notices-details.header')
@include('layouts.notices-details.content')
@include('general.footer')
@include('general.scripts')