@include('layouts.assignments-details.head')
@include('general.nav')
@include('layouts.assignments-details.header')
@include('layouts.assignments-details.content')
@include('general.footer')
@include('general.scripts')