@include('layouts.events-details.head')
@include('general.nav')
@include('layouts.events-details.header')
@include('layouts.events-details.content')
@include('general.footer')
@include('general.scripts')