@include('layouts.teacher-details.head')
@include('general.nav')
@include('layouts.teacher-details.header')
@include('layouts.teacher-details.content')
@include('general.footer')
@include('general.scripts')